### ISSUE TITLE
`rush build` does not generate any extension file on macOS and Linux

### ISSUE THREAD

**Issue by CRHUB** [ShreyashSaitwal/rush-cli#13] opened 2021-04-14 15:34 UTC
Hi Shreyash,

First of all a big thank you for your attempt to deliver a much simpler way creating App Inventor extension files. I have followed your instructions but I have the same issue as 'jaxparrow07'. There is no *.aix file. I also followed your further instructions to 'jaxparrow07' but still no such luck.

Kndrgrds, Johannes (Scotland, UK)

**Comment by ShreyashSaitwal** [comment] 2021-04-14 16:03
Hi,

Thanks for reporting. I was able to reproduce this issue on a Linux machine. I've identified the root caused and hopefully, the next update will ship with a fix for this. If everything goes as planned, I hope to release the update next week.

**Comment by CRHUB** [comment] 2021-04-14 17:05
Brilliant, thank you! The trouble with most software is that languages are easy to follow (most are similar) but the setup /dependencies etc are a nightmare.  Will donate $100.- (by PayPal) when I am able to create your example AIX file with Rush!

**Comment by ShreyashSaitwal** [comment] 2021-04-14 17:23
>  Will donate $100.- (by PayPal) when I am able to create your example AIX file with Rush!

Woah! Can't believe that! Thanks! 👍🏻

**Comment by jaxparrow07** [comment] 2021-04-21 06:28
Yeah, I am also waiting for the next release.

**Closed** 2021-04-27 10:47 UTC
Labels: bug

**Comment by ShreyashSaitwal** [comment] 2021-04-27 10:59
Hi @CRHUB and @jaxparrow07,
With the [latest release](https://github.com/ShreyashSaitwal/rush-cli/releases/tag/v1.1.0), this bug is now fixed. 
Check out the new installation instructions to update Rush 👉🏻  https://github.com/ShreyashSaitwal/rush-cli/wiki/Installation

**Comment by jaxparrow07** [comment] 2021-04-28 10:36
Thanks for your effort and work..
