### ISSUE TITLE
Installation Http status error [502]

### ISSUE THREAD

**Issue by CRHUB** [ShreyashSaitwal/rush-cli#16] opened 2021-04-27 12:05 UTC
<img width="944" alt="Screenshot 2021-04-27 at 12 57 50" src="https://user-images.githubusercontent.com/16798038/116238096-deb07900-a758-11eb-8cee-62c3f82f151f.png">

Hi Shreyash/Saitwal (apologies for not knowing how to address you!),
Thank you for the update but unfortunately I am not able to install the application.
Have attached screenshot which is self explanatory.
Kndrgrds, Johannes

**Comment by ShreyashSaitwal** [comment] 2021-04-27 12:46
Hi @CRHUB,
Can you please retry the same process?

> apologies for not knowing how to address you!

No worries. You can call me Shreyash.

**Comment by CRHUB** [comment] 2021-04-27 14:01
<img width="1253" alt="Screenshot 2021-04-27 at 14 57 08" src="https://user-images.githubusercontent.com/16798038/116254174-090a3280-a769-11eb-9950-ef6567296018.png">

Hi Shreyash,
Thank you for your quick response. I am now one step further i.e able to use 'create' command but no luck with 'build'. Have attached screenshot again. Kndrgrds, Hnk

**Comment by ShreyashSaitwal** [comment] 2021-04-27 14:03
Please install JDK version 8. Anything greater than it isn't currently supported.

**Comment by ShreyashSaitwal** [comment] 2021-04-27 15:31
@CRHUB, is your issue resolved?

**Comment by CRHUB** [comment] 2021-04-27 16:23
Hi Shreyash,

 

Have uninstalled JDK16 from my Mac and installed JDK8.

No doubt this will create issues with other programmes, that’s life!

 

I have been able to build an extension with the filename  test004.aix

Well done!!!

 

Imported the extension in AI but have hit another wall i.e 


Runtime Error

invoke: unable to invoke method `SumAllIntegers` in object of type boolean. Irritants: ()
Note: You will not see another error reported for 5 seconds.

 

This error occurred with an iPhone7.

Will try with an Android Phone.

 

Nevertheless, can you, please, provide me an email address for PayPal payment.

My email address is ***@***.***

 

Please keep my contact details private.

 

Kndrgrds,

Johannes

 

 

 

From: Shreyash Saitwal ***@***.***>
Reply to: ShreyashSaitwal/rush-cli ***@***.***>
Date: Tuesday, 27 April 2021 at 16:32
To: ShreyashSaitwal/rush-cli ***@***.***>
Cc: CRHUB ***@***.***>, Mention ***@***.***>
Subject: Re: [ShreyashSaitwal/rush-cli] Installation Http status error [502] (#16)

 

@CRHUB, is your issue resolved?

**Comment by CRHUB** [comment] 2021-04-27 16:38
From: Shreyash Saitwal ***@***.***>
Reply to: ShreyashSaitwal/rush-cli ***@***.***>
Date: Tuesday, 27 April 2021 at 16:32
To: ShreyashSaitwal/rush-cli ***@***.***>
Cc: CRHUB ***@***.***>, Mention ***@***.***>
Subject: Re: [ShreyashSaitwal/rush-cli] Installation Http status error [502] (#16)

 

@CRHUB, is your issue resolved?

**Comment by ShreyashSaitwal** [comment] 2021-04-27 16:39
> This error occurred with an iPhone7.

AFAIK, extension support isn't yet available for iOS in App Inventor.

> My email address is ***@***.***

Looks like GitHub censored your email. Nvm, you can contact me via Telegram: t.me/ShreyashSaitwal

**Comment by ShreyashSaitwal** [comment] 2021-04-27 16:51
Also, replace the code `SumAllIntegers` function in the sample extension with the following and then try it on Android:

```.java
public int Sum(int a, int b) {
    return a + b;
}
```

That function isn't correct and would throw errors. I forgot to update it in 1.1.0. 😅

**Comment by ShreyashSaitwal** [comment] 2021-04-28 09:37
Since the issue is now fixed, I'm closing it.

**Closed by ShreyashSaitwal** 2021-04-28 09:37 UTC
